version: "2.1"
volumes:
  xserver:
services:
  xserver:
    build: ./
    restart: always
    privileged: true
    volumes:
      - 'xserver:/tmp/.X11-unix'
  xeyes:
    build: ./example/xeyes
    restart: always
    volumes:
      - 'xserver:/tmp/.X11-unix'
